# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b31c6f45b00b3ba6b4f4cc464b2de9d488deac7c3ea6d872e442f92686b857dd86fd12850fc08f4255793ea1113f4fe40224c309a141b8f370abc5d380c848a2

test:
  secret_key_base: e219f248dd4256f7f24d283af1ef3c6d7db4196d11df515b0e9e1a3f0604f8743c678f14bf454f39f73ef73686a7d426ef8f5ad1a187bfc5c7306d10f09ca97e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
